### ISSUE TITLE
Escrever historias de usuario

### ISSUE THREAD

**Issue by rmobis** [rmobis/mc426#13]
Precisamos converter todas as issues referentes a features novas no nosso backlog para o formato de historias de usuario:

Como um **`papel`**
Eu quero/devo/gostaria de **`acao/funcao`**
De modo que **`valor agegado/beneficio esperado`**

**Comment by dsfugimoto** [comment]
Histórias escritas na Wiki

**Comment by brenofranca83** [comment]
Pessoal, escrevam as histórias nas issues. Wiki é fora do board, fica inviável manter o track depois de qual história está em qual parte do board.
